# Generated by Django 4.2.4 on 2023-08-08 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Football_Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=25)),
                ('top_speed', models.IntegerField()),
                ('preferred_foot', models.CharField(max_length=10)),
                ('injury_history', models.CharField(max_length=255)),
                ('video_url', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
