# Generated by Django 4.2.4 on 2023-08-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
