# Generated by Django 4.2.4 on 2023-08-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_alter_address_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this address should be treated as active. Unselect this instead of deleting address.', verbose_name='active'),
        ),
    ]
