# Generated by Django 4.2.4 on 2023-08-09 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_alter_address_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address_lane',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='football.address'),
        ),
    ]
