# Generated by Django 4.2.4 on 2023-08-09 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Football_Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=255)),
                ('games_played', models.IntegerField()),
                ('club_goals', models.IntegerField()),
                ('club_assists', models.IntegerField()),
                ('club_passes', models.IntegerField()),
                ('club_saved_goals', models.IntegerField()),
                ('interceptions_per_game', models.FloatField()),
                ('takles_per_game', models.FloatField()),
                ('shots_per_game', models.FloatField()),
                ('key_passes_per_game', models.FloatField()),
                ('dribles_completed_per_game', models.FloatField()),
                ('clean_sheets_per_game', models.FloatField()),
                ('club_yellow_card', models.IntegerField()),
                ('club_red_card', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Football_Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session', models.CharField(max_length=25)),
                ('football_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.football_club')),
                ('football_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.football_player')),
            ],
        ),
        migrations.AddField(
            model_name='football_player',
            name='session',
            field=models.ManyToManyField(blank=True, null=True, through='football.Football_Session', to='football.football_club'),
        ),
    ]
