# Generated by Django 4.2.4 on 2023-08-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0010_football_club_football_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='football_player',
            name='session',
            field=models.ManyToManyField(blank=True, through='football.Football_Session', to='football.football_club'),
        ),
    ]
