# Generated by Django 4.2.4 on 2023-08-10 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_alter_customuser_profile_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=25)),
                ('top_speed', models.IntegerField()),
                ('preferred_foot', models.CharField(max_length=10)),
                ('injury_history', models.CharField(max_length=255)),
                ('video_url', models.CharField(max_length=255)),
                ('football_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.football_club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
