# Generated by Django 4.2.4 on 2023-08-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='football_player',
            old_name='session',
            new_name='club_history',
        ),
        migrations.AddField(
            model_name='football_club',
            name='session',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
