# Generated by Django 4.2.4 on 2023-08-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_rename_session_football_player_club_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='football_player',
            name='football_history',
            field=models.ManyToManyField(blank=True, related_name='club', to='football.football_club'),
        ),
    ]
