# Generated by Django 4.2.4 on 2023-08-10 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0014_football_player_football_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=25)),
                ('top_speed', models.IntegerField()),
                ('preferred_foot', models.CharField(max_length=10)),
                ('injury_history', models.CharField(max_length=255)),
                ('video_url', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=255)),
                ('session', models.CharField(blank=True, max_length=25, null=True)),
                ('games_played', models.IntegerField(blank=True, null=True)),
                ('club_goals', models.IntegerField(blank=True, null=True)),
                ('club_assists', models.IntegerField(blank=True, null=True)),
                ('club_passes', models.IntegerField(blank=True, null=True)),
                ('club_saved_goals', models.IntegerField(blank=True, null=True)),
                ('interceptions_per_game', models.FloatField(blank=True, null=True)),
                ('takles_per_game', models.FloatField(blank=True, null=True)),
                ('shots_per_game', models.FloatField(blank=True, null=True)),
                ('key_passes_per_game', models.FloatField(blank=True, null=True)),
                ('dribles_completed_per_game', models.FloatField(blank=True, null=True)),
                ('clean_sheets_per_game', models.FloatField(blank=True, null=True)),
                ('club_yellow_card', models.IntegerField(blank=True, null=True)),
                ('club_red_card', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('players', models.ManyToManyField(blank=True, related_name='club', to='football.player')),
            ],
        ),
    ]
