# Generated by Django 4.2.4 on 2023-08-11 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_player_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='football_player',
            name='club_history',
        ),
        migrations.RemoveField(
            model_name='football_player',
            name='football_history',
        ),
        migrations.RemoveField(
            model_name='football_player',
            name='user',
        ),
        migrations.RemoveField(
            model_name='football_session',
            name='football_club',
        ),
        migrations.RemoveField(
            model_name='football_session',
            name='football_player',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='session',
            new_name='period',
        ),
        migrations.RemoveField(
            model_name='club',
            name='rating',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Football_Club',
        ),
        migrations.DeleteModel(
            name='Football_Player',
        ),
        migrations.DeleteModel(
            name='Football_Session',
        ),
        migrations.AddField(
            model_name='profilephoto',
            name='player_photo',
            field=models.ManyToManyField(blank=True, related_name='profile_image', to=settings.AUTH_USER_MODEL),
        ),
    ]
