# Generated by Django 4.2.4 on 2023-08-11 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_profilephoto_remove_football_player_club_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_photo',
        ),
    ]
