# Generated by Django 4.2.4 on 2023-08-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0017_remove_customuser_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilephoto',
            old_name='player_photo',
            new_name='player_id',
        ),
    ]
