# Generated by Django 4.2.4 on 2023-08-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0018_rename_player_photo_profilephoto_player_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilephoto',
            old_name='player_id',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='video_url',
        ),
        migrations.CreateModel(
            name='PlayerVideoClip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clip_url', models.TextField(blank=True, null=True)),
                ('player_id', models.ManyToManyField(blank=True, related_name='video_clip', to='football.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_position', models.CharField(max_length=25)),
                ('player_id', models.ManyToManyField(blank=True, related_name='position', to='football.player')),
            ],
        ),
    ]
