# Generated by Django 4.2.4 on 2023-08-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0019_rename_player_id_profilephoto_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='injury_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
