# Generated by Django 4.2.4 on 2023-08-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0020_player_league_alter_player_injury_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='league',
        ),
        migrations.AddField(
            model_name='club',
            name='league',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
