# Generated by Django 4.2.4 on 2023-08-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0021_remove_player_league_club_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCareerHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('debut_date', models.DateField()),
                ('last_date', models.DateField()),
                ('league_name', models.CharField(max_length=255)),
                ('club_name', models.CharField(max_length=255)),
                ('player_id', models.ManyToManyField(blank=True, related_name='carreer_history', to='football.player')),
            ],
        ),
    ]
