# Generated by Django 4.2.4 on 2023-08-16 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0023_alter_playercareerhistory_last_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballTournaments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tournaments_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SportProfileType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this address should be treated as active. Unselect this instead of deleting address.', verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='FootballCoachCareerHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=25)),
                ('games_played_as_player', models.IntegerField()),
                ('games_won_as_player', models.IntegerField()),
                ('games_lost_as_player', models.IntegerField()),
                ('games_tied_as_player', models.IntegerField()),
                ('playoffs_games_played_as_player', models.IntegerField()),
                ('tournaments_won_as_player', models.IntegerField()),
                ('tournaments_name', models.ManyToManyField(to='football.footballtournaments')),
            ],
        ),
        migrations.CreateModel(
            name='FootballCoach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_date', models.IntegerField()),
                ('to_date', models.IntegerField()),
                ('playoffs_games_coached_in', models.IntegerField()),
                ('playoffs_games_won', models.IntegerField()),
                ('playoffs_games_lost', models.IntegerField()),
                ('current_team', models.CharField(max_length=255)),
                ('acheivements', models.ManyToManyField(blank=True, to='football.footballtournaments')),
                ('carreer_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='football.footballcoachcareerhistory')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='football.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='sport_profile_type',
            field=models.ManyToManyField(blank=True, to='football.sportprofiletype'),
        ),
    ]
