# Generated by Django 4.2.4 on 2023-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0024_footballtournaments_sportprofiletype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAcheivements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acheivement_name', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='personal_acheivements',
            field=models.ManyToManyField(blank=True, to='football.playeracheivements'),
        ),
    ]
