# Generated by Django 4.2.4 on 2023-08-17 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0025_playeracheivements_player_personal_acheivements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='sport_profile_type',
        ),
        migrations.AddField(
            model_name='sportprofiletype',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sport_profile_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
