# Generated by Django 4.2.4 on 2023-08-17 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0026_remove_customuser_sport_profile_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportprofiletype',
            name='user_id',
        ),
        migrations.AddField(
            model_name='sportprofiletype',
            name='user_id',
            field=models.ManyToManyField(blank=True, related_name='sport_profile_type', to=settings.AUTH_USER_MODEL),
        ),
    ]
