# Generated by Django 4.2.4 on 2023-08-17 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0028_remove_sportprofiletype_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='permanent_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='football.address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='present_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='present_address', to='football.address'),
        ),
    ]
