# Generated by Django 4.2.4 on 2023-08-17 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0029_alter_customuser_permanent_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='present_address',
        ),
        migrations.AddField(
            model_name='address',
            name='permanent_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='present_user_id',
            field=models.ManyToManyField(blank=True, related_name='present_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
