# Generated by Django 4.2.4 on 2023-08-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0030_remove_customuser_permanent_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballcoachcareerhistory',
            name='tournaments_name',
        ),
        migrations.RemoveField(
            model_name='footballcoachcareerhistory',
            name='tournaments_won_as_player',
        ),
        migrations.AddField(
            model_name='footballcoach',
            name='total_no_tournaments_won_as_coach',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballcoach',
            name='tournaments_name_won_as_coach',
            field=models.ManyToManyField(blank=True, to='football.footballtournaments'),
        ),
        migrations.AddField(
            model_name='footballcoachcareerhistory',
            name='total_no_tournaments_won_as_player',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballcoachcareerhistory',
            name='tournaments_name_won_as_player',
            field=models.ManyToManyField(blank=True, to='football.footballtournaments'),
        ),
        migrations.AlterField(
            model_name='footballcoach',
            name='acheivements',
            field=models.ManyToManyField(blank=True, to='football.playeracheivements'),
        ),
        migrations.AlterField(
            model_name='footballcoach',
            name='current_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footballcoach',
            name='playoffs_games_coached_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballcoach',
            name='playoffs_games_lost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballcoach',
            name='playoffs_games_won',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballcoachcareerhistory',
            name='games_lost_as_player',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballcoachcareerhistory',
            name='games_played_as_player',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballcoachcareerhistory',
            name='games_tied_as_player',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballcoachcareerhistory',
            name='games_won_as_player',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballcoachcareerhistory',
            name='period',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='footballcoachcareerhistory',
            name='playoffs_games_played_as_player',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
