# Generated by Django 4.2.4 on 2023-08-18 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0031_remove_footballcoachcareerhistory_tournaments_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballClub',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('founded_in', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FootballClubOfficeBearer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='office_bearer', to='football.footballclub')),
            ],
        ),
        migrations.CreateModel(
            name='FootballClubHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=25)),
                ('league_name', models.CharField(max_length=255)),
                ('games_played', models.IntegerField()),
                ('games_won', models.IntegerField(blank=True, null=True)),
                ('games_lost', models.IntegerField(blank=True, null=True)),
                ('games_tied', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(max_length=100)),
                ('club_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='club_history', to='football.footballclub')),
            ],
        ),
    ]
