# Generated by Django 4.2.4 on 2023-08-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0032_footballclub_footballclubofficebearer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
