# Generated by Django 4.2.4 on 2023-08-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0035_alter_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
