# Generated by Django 4.2.4 on 2023-09-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0037_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='playervideoclip',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
