# Generated by Django 4.2.4 on 2023-09-03 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0038_playervideoclip_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playervideoclip',
            name='player_id',
        ),
        migrations.AddField(
            model_name='playervideoclip',
            name='user_id',
            field=models.ManyToManyField(blank=True, related_name='video_clip', to=settings.AUTH_USER_MODEL),
        ),
    ]
