# Generated by Django 4.2.4 on 2023-09-05 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0040_profiledescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='personal_acheivements',
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
    ]
