# Generated by Django 4.2.4 on 2023-09-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0041_remove_player_personal_acheivements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='primary_position',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='secondary_position',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='top_speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PlayerPosition',
        ),
    ]
