# Generated by Django 4.2.4 on 2023-09-05 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0042_player_primary_position_player_secondary_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercareerhistory',
            name='player_id',
        ),
        migrations.AddField(
            model_name='playercareerhistory',
            name='player_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carreer_history', to='football.player'),
        ),
    ]
