# Generated by Django 4.2.4 on 2023-09-06 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0043_remove_playercareerhistory_player_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='players',
        ),
        migrations.AddField(
            model_name='club',
            name='players',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to='football.player'),
        ),
    ]
