# Generated by Django 4.2.4 on 2023-09-06 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0044_remove_club_players_club_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acheivements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acheivement_name', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='footballcoach',
            name='acheivements',
        ),
        migrations.DeleteModel(
            name='PlayerAcheivements',
        ),
        migrations.AddField(
            model_name='acheivements',
            name='coach_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_acheivements', to='football.footballcoach'),
        ),
        migrations.AddField(
            model_name='acheivements',
            name='player_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_acheivements', to='football.player'),
        ),
    ]
