# Generated by Django 4.2.4 on 2023-09-10 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0047_remove_footballcoach_carreer_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballtournaments',
            name='no_of_times',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballtournaments',
            name='tournaments_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='footballtournaments',
            name='tournaments_won_as_coach',
        ),
        migrations.RemoveField(
            model_name='footballtournaments',
            name='tournaments_won_as_player',
        ),
        migrations.AddField(
            model_name='footballtournaments',
            name='tournaments_won_as_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_name_won_as_coach', to='football.footballcoach'),
        ),
        migrations.AddField(
            model_name='footballtournaments',
            name='tournaments_won_as_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_name_won_as_player', to='football.footballcoachcareerhistory'),
        ),
    ]
