# Generated by Django 4.2.4 on 2023-09-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0048_footballtournaments_no_of_times_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballtournaments',
            old_name='tournaments_won_as_player',
            new_name='coach_career_history_id',
        ),
        migrations.RenameField(
            model_name='footballtournaments',
            old_name='tournaments_won_as_coach',
            new_name='coach_id',
        ),
    ]
