# Generated by Django 4.2.4 on 2023-09-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0049_rename_tournaments_won_as_player_footballtournaments_coach_career_history_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playervideoclip',
            name='profile_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
