# Generated by Django 4.2.4 on 2023-09-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0050_playervideoclip_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo_url',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
