# Generated by Django 4.2.4 on 2023-09-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0051_customuser_profile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
