# Generated by Django 4.2.4 on 2023-09-26 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0054_mynetworkrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mynetworkrequest',
            old_name='fromUser',
            new_name='form_user',
        ),
        migrations.RenameField(
            model_name='mynetworkrequest',
            old_name='toUser',
            new_name='to_user',
        ),
    ]
