# Generated by Django 4.2.4 on 2023-10-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0055_rename_fromuser_mynetworkrequest_form_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mynetworkrequest',
            old_name='form_user',
            new_name='from_user',
        ),
    ]
