# Generated by Django 4.2.4 on 2023-10-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0056_rename_form_user_mynetworkrequest_from_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynetworkrequest',
            name='from_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mynetworkrequest',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mynetworkrequest',
            name='to_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
