# Generated by Django 4.2.4 on 2023-10-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0058_remove_mynetworkrequest_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynetworkrequest',
            name='from_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mynetworkrequest',
            name='to_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
