# Generated by Django 4.2.4 on 2023-10-05 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0059_alter_mynetworkrequest_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynetworkrequest',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
