# Generated by Django 4.2.4 on 2023-10-05 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0060_alter_mynetworkrequest_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynetworkrequest',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mynetworkrequest',
            name='to_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
