# Generated by Django 4.2.4 on 2023-10-05 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0061_alter_mynetworkrequest_from_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkConnected',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('connected_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
