# Generated by Django 4.2.4 on 2023-10-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0063_remove_networkconnected_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkconnected',
            old_name='connected_to',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='networkconnected',
            name='connect_to_user1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkconnected',
            name='connect_to_user2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
