# Generated by Django 4.2.4 on 2023-10-06 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0064_rename_connected_to_networkconnected_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkconnected',
            name='user_id',
        ),
        migrations.AddField(
            model_name='networkconnected',
            name='user_id',
            field=models.ManyToManyField(blank=True, related_name='connected_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
