# Generated by Django 4.2.4 on 2023-10-09 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0065_remove_networkconnected_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkconnected',
            name='connect_to_user1',
        ),
        migrations.RemoveField(
            model_name='networkconnected',
            name='connect_to_user2',
        ),
        migrations.AddField(
            model_name='networkconnected',
            name='connect_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
