# Generated by Django 4.2.4 on 2023-10-09 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0066_remove_networkconnected_connect_to_user1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkconnected',
            name='user_id',
        ),
        migrations.AddField(
            model_name='networkconnected',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
