# Generated by Django 4.2.4 on 2023-10-17 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0067_remove_networkconnected_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acheivements',
            name='acheivement_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acheivements',
            name='period',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='footballclub',
            name='founded_in',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballclub',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='footballclubhistory',
            name='club_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_history', to='football.footballclub'),
        ),
        migrations.AlterField(
            model_name='footballclubhistory',
            name='games_played',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballclubhistory',
            name='league_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footballclubhistory',
            name='period',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='footballclubhistory',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='footballclubofficebearer',
            name='club_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_bearer', to='football.footballclub'),
        ),
        migrations.AlterField(
            model_name='footballclubofficebearer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='footballclubofficebearer',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='footballcoach',
            name='current_team',
            field=models.TextField(blank=True, null=True),
        ),
    ]
