# Generated by Django 4.2.4 on 2023-10-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0068_alter_acheivements_acheivement_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballcoach',
            name='from_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballcoach',
            name='to_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
