# Generated by Django 4.2.4 on 2023-10-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0069_alter_footballcoach_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballcoach',
            name='current_club_inside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_club', to='football.footballclub'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_club_inside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_club', to='football.footballclub'),
        ),
    ]
