# Generated by Django 4.2.4 on 2023-10-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0070_footballcoach_current_club_inside_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballcoach',
            name='current_club_inside',
        ),
    ]
