# Generated by Django 4.2.4 on 2023-10-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0072_footballcoach_current_club_inside'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballcoach',
            name='current_club_inside',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_club_inside',
        ),
        migrations.AddField(
            model_name='footballcoach',
            name='current_club_inside',
            field=models.ManyToManyField(blank=True, related_name='coach_club', to='football.footballclub'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_club_inside',
            field=models.ManyToManyField(blank=True, related_name='player_club', to='football.footballclub'),
        ),
    ]
