# Generated by Django 4.2.4 on 2023-10-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0075_player_current_club_outside'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballcoach',
            name='current_club_inside',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_club_inside',
        ),
    ]
