# Generated by Django 4.2.4 on 2023-10-18 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0076_remove_footballcoach_current_club_inside_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='current_club_outside',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_club_outside',
            field=models.TextField(blank=True, null=True),
        ),
    ]
