# Generated by Django 4.2.4 on 2023-10-18 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0077_remove_player_current_club_outside_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='current_club_outside',
        ),
    ]
