# Generated by Django 4.2.4 on 2023-10-18 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0078_remove_customuser_current_club_outside'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_club_inside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_club', to='football.footballclub'),
        ),
        migrations.AddField(
            model_name='player',
            name='current_club_outside',
            field=models.TextField(blank=True, null=True),
        ),
    ]
