# Generated by Django 4.2.4 on 2023-10-18 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0080_footballcoach_current_club_inside'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FootballCoach',
            new_name='FootballCoachInfo',
        ),
    ]
