# Generated by Django 4.2.4 on 2023-10-18 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0082_rename_footballcoachinfo_footballcoach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acheivements',
            name='coach_id',
        ),
        migrations.RemoveField(
            model_name='footballcoachcareerhistory',
            name='coach_id',
        ),
        migrations.RemoveField(
            model_name='footballtournaments',
            name='coach_id',
        ),
        migrations.DeleteModel(
            name='FootballCoach',
        ),
    ]
