# Generated by Django 4.2.4 on 2023-10-18 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0084_footballcoach_acheivements_coach_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballcoach',
            name='current_club_inside',
        ),
    ]
