# Generated by Django 4.2.4 on 2023-10-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0085_remove_footballcoach_current_club_inside'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballcoach',
            name='user',
        ),
    ]
