# Generated by Django 4.2.4 on 2023-10-18 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0086_remove_footballcoach_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballcoach',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach', to=settings.AUTH_USER_MODEL),
        ),
    ]
