# Generated by Django 4.2.4 on 2023-10-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0087_footballcoach_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballcoach',
            name='current_team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
