# Generated by Django 4.2.4 on 2023-10-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0088_alter_footballcoach_current_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballcoach',
            name='current_team',
            field=models.TextField(blank=True, null=True),
        ),
    ]
