# Generated by Django 4.2.4 on 2023-10-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0090_footballcoach_current_club_inside'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
