# Generated by Django 4.2.4 on 2023-10-19 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0092_referenceoutside_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referenceoutside',
            old_name='name',
            new_name='reference_name',
        ),
    ]
