# Generated by Django 4.2.4 on 2023-10-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0093_rename_name_referenceoutside_reference_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballcoach',
            name='current_club_inside',
        ),
        migrations.RemoveField(
            model_name='player',
            name='current_club_inside',
        ),
        migrations.AddField(
            model_name='footballclub',
            name='coach_id',
            field=models.ManyToManyField(blank=True, related_name='coach_current_club_inside', to='football.footballcoach'),
        ),
        migrations.AddField(
            model_name='footballclub',
            name='player_id',
            field=models.ManyToManyField(blank=True, related_name='player_current_club_inside', to='football.player'),
        ),
    ]
