# Generated by Django 4.2.4 on 2023-10-20 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0095_remove_footballclub_coach_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentOutside',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=12, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_outside', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_inside', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='agent_inside',
            field=models.ManyToManyField(blank=True, related_name='agent_info_inside', to='football.agent'),
        ),
        migrations.AddField(
            model_name='player',
            name='agent_outside',
            field=models.ManyToManyField(blank=True, related_name='agent_info_outside', to='football.agentoutside'),
        ),
    ]
