# Generated by Django 4.2.4 on 2023-10-20 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0096_agentoutside_agent_player_agent_inside_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentoutside',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='agent_outside',
        ),
        migrations.AddField(
            model_name='agentoutside',
            name='player_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_outside', to='football.player'),
        ),
    ]
