# Generated by Django 4.2.4 on 2023-10-22 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0097_remove_agentoutside_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='user_id',
        ),
        migrations.AddField(
            model_name='player',
            name='reference_inside',
            field=models.ManyToManyField(blank=True, related_name='reference_info_inside', to='football.reference'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referenceoutside',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_users_outside', to='football.player'),
        ),
    ]
