# Generated by Django 4.2.4 on 2023-10-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0099_rename_user_id_referenceoutside_player_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_club_inside',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
