# Generated by Django 4.2.4 on 2023-10-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0100_alter_player_current_club_inside'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
