# Generated by Django 4.2.4 on 2023-10-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0101_club_club_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
