# Generated by Django 4.2.4 on 2023-10-30 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0102_club_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('to_user', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
