# Generated by Django 4.2.4 on 2023-11-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0103_verifyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
