# Generated by Django 4.2.4 on 2023-11-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0104_club_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyrequest',
            name='profile_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
