# Generated by Django 4.2.4 on 2023-11-04 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0105_verifyrequest_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyrequest',
            name='club_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='football.club'),
        ),
    ]
