# Generated by Django 4.2.4 on 2023-11-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0106_verifyrequest_club_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballcoachcareerhistory',
            old_name='games_lost_as_player',
            new_name='club_id',
        ),
        migrations.RenameField(
            model_name='footballcoachcareerhistory',
            old_name='games_played_as_player',
            new_name='playoffs_games_coached_in',
        ),
        migrations.RenameField(
            model_name='footballcoachcareerhistory',
            old_name='games_tied_as_player',
            new_name='playoffs_games_lost',
        ),
        migrations.RenameField(
            model_name='footballcoachcareerhistory',
            old_name='games_won_as_player',
            new_name='playoffs_games_won',
        ),
        migrations.RenameField(
            model_name='footballcoachcareerhistory',
            old_name='playoffs_games_played_as_player',
            new_name='total_no_tournaments_won_as_coach',
        ),
        migrations.RemoveField(
            model_name='footballcoachcareerhistory',
            name='total_no_tournaments_won_as_player',
        ),
        migrations.AddField(
            model_name='footballcoachcareerhistory',
            name='club_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='footballcoachcareerhistory',
            name='league',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='footballcoachcareerhistory',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballcoachcareerhistory',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='footballcoachcareerhistory',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
