# Generated by Django 4.2.4 on 2023-11-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0107_rename_games_lost_as_player_footballcoachcareerhistory_club_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballcoach',
            name='current_club_inside',
        ),
        migrations.AddField(
            model_name='footballcoach',
            name='current_team_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
