# Generated by Django 4.2.4 on 2023-11-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0109_verifyrequest_coach_club_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_club_inside_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
