# Generated by Django 4.2.4 on 2023-12-05 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import football.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0111_alter_footballcoach_current_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=football.models.user_directory_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.ManyToManyField(blank=True, related_name='comments', to='football.postcomments')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
