# Generated by Django 4.2.4 on 2023-12-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0113_remove_postitem_comments_postcomments_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
