# Generated by Django 4.2.4 on 2023-12-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0114_postitem_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
