# Generated by Django 4.2.4 on 2023-12-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0116_postcomments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
