# Generated by Django 4.2.4 on 2023-12-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0118_remove_postitem_likes_postlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomments',
            name='post_id',
        ),
        migrations.AddField(
            model_name='postcomments',
            name='post_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='football.postitem'),
        ),
    ]
