# Generated by Django 4.2.4 on 2024-01-03 12:59

from django.db import migrations, models
import football.models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0121_remove_news_user_news_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=football.models.user_directory_path),
        ),
    ]
