# Generated by Django 4.2.4 on 2024-01-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0122_news_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='event'),
        ),
    ]
