# Generated by Django 4.2.4 on 2024-01-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0124_remove_news_user_news_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkconnected',
            name='network_request_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
