# Generated by Django 4.2.4 on 2024-01-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0126_alter_address_address_lane_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='top_speed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
