# Generated by Django 4.2.4 on 2024-01-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0127_alter_player_top_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='current_club_inside',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
