# Generated by Django 4.2.4 on 2024-01-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0128_alter_player_current_club_inside'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledescription',
            name='profile_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
