# Generated by Django 4.2.4 on 2024-01-19 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0130_remove_footballclub_founded_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='acheivements',
            name='club_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_acheivements', to='football.footballclub'),
        ),
    ]
