# Generated by Django 4.2.4 on 2024-01-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0131_acheivements_club_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
