# Generated by Django 4.2.4 on 2024-02-20 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0133_customuser_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
    ]
