# Generated by Django 4.2.4 on 2024-02-20 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0134_remove_customuser_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_open_for_hiring',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
