# Generated by Django 4.2.4 on 2024-02-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0136_remove_customuser_is_open_for_hiring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballcoach',
            name='is_open_for_hiring',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballcoach',
            name='my_worth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
