# Generated by Django 4.2.4 on 2024-02-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0137_footballcoach_is_open_for_hiring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='current_club',
            field=models.TextField(blank=True, null=True),
        ),
    ]
