# Generated by Django 4.2.4 on 2024-03-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0139_alter_player_primary_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.CharField(blank=True, null=True),
        ),
    ]
