# Generated by Django 4.2.4 on 2024-04-10 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0140_agentcareerhistory_agentlicense_coachlicense_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('helpid', models.AutoField(primary_key=True, serialize=False)),
                ('typeOfHelp', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('oppid', models.AutoField(primary_key=True, serialize=False)),
                ('opportunity_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityApplications',
            fields=[
                ('opapplicationID', models.AutoField(primary_key=True, serialize=False)),
                ('appliedOn', models.DateField()),
                ('comment', models.TextField()),
                ('opportunityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.opportunity')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelpSupports',
            fields=[
                ('helpSupportID', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helpComments', models.TextField()),
                ('helpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.help')),
                ('helpProvidedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
