# Generated by Django 4.2.4 on 2024-03-11 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0140_alter_address_pin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAcheivements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acheivement_name', models.CharField(blank=True, max_length=255, null=True)),
                ('period', models.CharField(blank=True, max_length=25, null=True)),
                ('profile_type', models.CharField(blank=True, max_length=25, null=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_acheivements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
