# Generated by Django 4.2.4 on 2024-04-10 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0141_help_opportunity_opportunityapplications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessScore',
            fields=[
                ('wellnessid', models.AutoField(primary_key=True, serialize=False)),
                ('mood', models.CharField(max_length=50)),
                ('canManage', models.CharField(max_length=10)),
                ('canHandlePressure', models.CharField(max_length=10)),
                ('sleepHours', models.IntegerField()),
                ('energyLevel', models.CharField(max_length=10)),
                ('haveSupport', models.CharField(max_length=10)),
                ('feelConnected', models.CharField(max_length=10)),
                ('knowResourcesForSupport', models.CharField(max_length=10)),
                ('needSupport', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
