# Generated by Django 4.2.4 on 2024-04-10 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0142_wellnessscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={'managed': False},
        ),
    ]
