# Generated by Django 4.2.4 on 2024-03-14 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0142_personalachievements_delete_personalacheivements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sport_type', models.CharField(max_length=50)),
                ('league_name', models.CharField(max_length=255)),
                ('league_type', models.CharField(max_length=100)),
                ('league_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='football.country')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('reg_id', models.CharField(max_length=50, unique=True)),
                ('league_id', models.ManyToManyField(blank=True, null=True, related_name='teams', to='football.league')),
            ],
        ),
    ]
