# Generated by Django 4.2.4 on 2024-03-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0143_country_league_alter_address_pin_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='league_id',
        ),
        migrations.AddField(
            model_name='league',
            name='country_id',
            field=models.ManyToManyField(blank=True, null=True, related_name='leagues', to='football.country'),
        ),
    ]
