# Generated by Django 4.2.4 on 2024-04-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0143_alter_help_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={},
        ),
        migrations.AlterField(
            model_name='wellnessscore',
            name='energyLevel',
            field=models.IntegerField(),
        ),
    ]
