# Generated by Django 4.2.4 on 2024-04-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0144_alter_help_options_alter_wellnessscore_energylevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessscore',
            name='canManage',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10),
        ),
    ]
