# Generated by Django 4.2.4 on 2024-03-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0144_remove_league_league_id_league_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='country_id',
            field=models.ManyToManyField(blank=True, related_name='leagues', to='football.country'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league_id',
            field=models.ManyToManyField(blank=True, related_name='teams', to='football.league'),
        ),
    ]
