# Generated by Django 4.2.4 on 2024-04-10 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0145_alter_wellnessscore_canmanage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellnessscore',
            name='canManage',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.CreateModel(
            name='ConditioningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(max_length=50)),
                ('duration_minutes', models.IntegerField()),
                ('intensity', models.CharField(max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('heart_rate_bpm', models.IntegerField(blank=True, null=True)),
                ('calories_burned', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pre_session_mood', models.CharField(blank=True, max_length=20)),
                ('post_session_mood', models.CharField(blank=True, max_length=20)),
                ('equipment_used', models.CharField(blank=True, max_length=100)),
                ('injuries_discomfort', models.TextField(blank=True)),
                ('sleep_hours', models.IntegerField(blank=True, null=True)),
                ('water_intake_inlts', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
