# Generated by Django 4.2.4 on 2024-04-12 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0146_alter_wellnessscore_canmanage_conditioninglog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportprofiletype',
            name='priority',
        ),
    ]
