# Generated by Django 4.2.4 on 2024-03-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0146_remove_type_player_type_team_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
