# Generated by Django 4.2.4 on 2024-03-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0147_club_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='league_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sport_type',
        ),
        migrations.AddField(
            model_name='team',
            name='sport_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
