# Generated by Django 4.2.4 on 2024-04-12 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0148_sportprofiletype_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportprofiletype',
            name='priority',
        ),
    ]
