# Generated by Django 4.2.4 on 2024-03-20 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0148_remove_league_country_id_remove_team_league_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='country',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='league',
            new_name='league_name',
        ),
        migrations.RenameField(
            model_name='club',
            old_name='type',
            new_name='league_type',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='club_name',
        ),
    ]
