# Generated by Django 4.2.4 on 2024-04-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0149_remove_sportprofiletype_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportprofiletype',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
