# Generated by Django 4.2.4 on 2024-03-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0149_rename_country_club_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
