# Generated by Django 4.2.4 on 2024-04-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0150_sportprofiletype_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunityapplications',
            old_name='userID',
            new_name='actedBy',
        ),
    ]
