# Generated by Django 4.2.4 on 2024-03-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0150_club_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='sport_type',
            field=models.TextField(),
        ),
    ]
