# Generated by Django 4.2.4 on 2024-04-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0151_rename_userid_opportunityapplications_actedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityapplications',
            name='applied',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunityapplications',
            name='saved',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
