# Generated by Django 4.2.4 on 2024-03-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0152_rename_current_team_footballcoach_coach_license_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportLicense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
