# Generated by Django 4.2.4 on 2024-04-12 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0152_opportunityapplications_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='club',
            name='to_year',
        ),
    ]
