# Generated by Django 4.2.4 on 2024-03-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0153_sportlicense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballcoach',
            old_name='coach_license',
            new_name='license_name',
        ),
    ]
