# Generated by Django 4.2.4 on 2024-03-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0154_rename_coach_license_footballcoach_license_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballcoach',
            name='license_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
