# Generated by Django 4.2.4 on 2024-03-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0155_footballcoach_license_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballcoachcareerhistory',
            name='league_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
