# Generated by Django 4.2.4 on 2024-03-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0156_footballcoachcareerhistory_league_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballcoachcareerhistory',
            name='club_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='footballcoachcareerhistory',
            name='league_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
