# Generated by Django 4.2.4 on 2024-03-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0157_alter_footballcoachcareerhistory_club_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='league_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
