# Generated by Django 4.2.4 on 2024-03-30 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0158_club_league_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentoutside',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='personalachievements',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='playercareerhistory',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='reference',
            name='reffered_user',
        ),
        migrations.RemoveField(
            model_name='referenceoutside',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='player_id',
        ),
        migrations.AddField(
            model_name='agent',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='cerificate'),
        ),
        migrations.AddField(
            model_name='agent',
            name='country_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='license_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='license_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Acheivements',
        ),
        migrations.DeleteModel(
            name='AgentOutside',
        ),
        migrations.DeleteModel(
            name='PersonalAchievements',
        ),
        migrations.DeleteModel(
            name='PlayerCareerHistory',
        ),
        migrations.DeleteModel(
            name='Reference',
        ),
        migrations.DeleteModel(
            name='ReferenceOutside',
        ),
    ]
