# Generated by Django 4.2.4 on 2024-04-02 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0159_remove_agentoutside_player_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='license_id',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='license_name',
        ),
        migrations.RemoveField(
            model_name='footballcoach',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='footballcoach',
            name='license_id',
        ),
        migrations.RemoveField(
            model_name='footballcoach',
            name='license_name',
        ),
        migrations.AlterField(
            model_name='agent',
            name='country_name',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CoachLicense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_id', models.IntegerField(blank=True, null=True)),
                ('license_name', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='cerificate')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_license', to='football.footballcoach')),
            ],
        ),
        migrations.CreateModel(
            name='AgentLicense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('license_id', models.IntegerField(blank=True, null=True)),
                ('license_name', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='cerificate')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_license', to='football.agent')),
            ],
        ),
    ]
