# Generated by Django 4.2.4 on 2024-04-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0161_agentcareerhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcareerhistory',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
