# Generated by Django 4.2.4 on 2024-04-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0162_agentcareerhistory_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcareerhistory',
            name='contact_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
