# Generated by Django 4.2.4 on 2024-04-06 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0163_agentcareerhistory_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballPlayersAndCoachesUnderMe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sport_profile', models.CharField(blank=True, max_length=25, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_and_coaches_under_me', to='football.footballcoach')),
            ],
        ),
    ]
