# Generated by Django 4.2.4 on 2024-04-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0164_footballplayersandcoachesunderme'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballplayersandcoachesunderme',
            name='is_notable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
