# Generated by Django 4.2.4 on 2024-04-06 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0165_footballplayersandcoachesunderme_is_notable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballplayersandcoachesunderme',
            name='coach',
        ),
        migrations.AddField(
            model_name='footballplayersandcoachesunderme',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_and_coaches_under_me', to='football.agent'),
        ),
    ]
