# Generated by Django 4.2.4 on 2024-04-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0166_remove_footballplayersandcoachesunderme_coach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='period',
        ),
        migrations.AddField(
            model_name='club',
            name='from_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='to_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
