# Generated by Django 4.2.4 on 2024-04-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0168_remove_agentcareerhistory_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportprofiletype',
            name='priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
