# Generated by Django 4.2.4 on 2024-04-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0169_sportprofiletype_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportprofiletype',
            old_name='priority',
            new_name='status',
        ),
    ]
