# Generated by Django 4.2.4 on 2024-04-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0170_rename_priority_sportprofiletype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportprofiletype',
            name='status',
            field=models.CharField(blank=True, default='Not current', max_length=50, null=True),
        ),
    ]
