# Generated by Django 4.2.4 on 2024-04-30 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0171_alter_sportprofiletype_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('helpid', models.AutoField(primary_key=True, serialize=False)),
                ('typeOfHelp', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('oppid', models.AutoField(primary_key=True, serialize=False)),
                ('opportunity_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WellnessScore',
            fields=[
                ('wellnessid', models.AutoField(primary_key=True, serialize=False)),
                ('mood', models.CharField(max_length=50)),
                ('canManage', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('canHandlePressure', models.CharField(max_length=10)),
                ('sleepHours', models.IntegerField()),
                ('energyLevel', models.IntegerField()),
                ('haveSupport', models.CharField(max_length=10)),
                ('feelConnected', models.CharField(max_length=10)),
                ('knowResourcesForSupport', models.CharField(max_length=10)),
                ('needSupport', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityApplications',
            fields=[
                ('opapplicationID', models.AutoField(primary_key=True, serialize=False)),
                ('saved', models.IntegerField(blank=True, null=True)),
                ('applied', models.IntegerField(blank=True, null=True)),
                ('appliedOn', models.DateField()),
                ('comment', models.TextField()),
                ('actedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('opportunityID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.opportunity')),
            ],
        ),
        migrations.CreateModel(
            name='HelpSupports',
            fields=[
                ('helpSupportID', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helpComments', models.TextField()),
                ('helpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.help')),
                ('helpProvidedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConditioningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('activity_type', models.CharField(max_length=50)),
                ('duration_minutes', models.IntegerField()),
                ('intensity', models.CharField(max_length=20)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('heart_rate_bpm', models.IntegerField(blank=True, null=True)),
                ('calories_burned', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('pre_session_mood', models.CharField(blank=True, max_length=20)),
                ('post_session_mood', models.CharField(blank=True, max_length=20)),
                ('equipment_used', models.CharField(blank=True, max_length=100)),
                ('injuries_discomfort', models.TextField(blank=True)),
                ('sleep_hours', models.IntegerField(blank=True, null=True)),
                ('water_intake_inlts', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
