# Generated by Django 4.2.4 on 2024-05-04 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0172_help_opportunity_wellnessscore_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sportprofiletype',
            old_name='user_id',
            new_name='user',
        ),
    ]
