# Generated by Django 4.2.4 on 2024-05-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0173_rename_user_id_sportprofiletype_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
