# Generated by Django 4.2.4 on 2024-05-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0175_footballcoachcareerhistory_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcareerhistory',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
