# Generated by Django 4.2.4 on 2024-05-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0176_agentcareerhistory_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='postitem',
            name='post_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
