# Generated by Django 4.2.4 on 2024-05-31 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0178_news_attending_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='attending_persons',
        ),
    ]
