# Generated by Django 4.2.4 on 2024-06-06 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0181_remove_footballplayersandcoachesunderme_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballplayersandcoachesunderme',
            name='agent_career_history',
        ),
    ]
