# Generated by Django 4.2.4 on 2024-06-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0183_footballplayersandcoachesunderme_agent_career_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballplayersandcoachesunderme',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='footballplayersandcoachesunderme',
            old_name='sport_profile',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='footballplayersandcoachesunderme',
            name='user_id',
        ),
    ]
