# Generated by Django 4.2.4 on 2024-06-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0184_rename_user_name_footballplayersandcoachesunderme_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballplayersandcoachesunderme',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
