# Generated by Django 4.2.4 on 2024-06-13 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0185_footballplayersandcoachesunderme_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballAgentEndorsementRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_requester', models.IntegerField(blank=True, null=True)),
                ('to_endorser', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('agent_players_coaches_under_me', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsement_request', to='football.footballplayersandcoachesunderme')),
                ('endorsee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
