# Generated by Django 4.2.4 on 2024-06-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0186_footballagentendorsementrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballagentendorsementrequest',
            name='to_endorser_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
