# Generated by Django 4.2.4 on 2024-06-14 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0187_footballagentendorsementrequest_to_endorser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballagentendorsementrequest',
            name='to_endorser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorser', to=settings.AUTH_USER_MODEL),
        ),
    ]
