# Generated by Django 4.2.4 on 2024-06-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0188_alter_footballagentendorsementrequest_to_endorser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballagentendorsementrequest',
            old_name='endorsee',
            new_name='from_endorsee',
        ),
        migrations.RemoveField(
            model_name='footballagentendorsementrequest',
            name='from_requester',
        ),
    ]
