# Generated by Django 4.2.4 on 2024-06-22 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0189_rename_endorsee_footballagentendorsementrequest_from_endorsee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballPlayerEndorsementRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('to_endorser_email', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('from_endorsee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_endorsee', to=settings.AUTH_USER_MODEL)),
                ('player_career_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsement_request', to='football.club')),
                ('to_endorser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_club_endorser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FootballCoachEndorsementRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('to_endorser_email', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('coach_career_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endorsement_request', to='football.footballcoachcareerhistory')),
                ('from_endorsee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_endorsee', to=settings.AUTH_USER_MODEL)),
                ('to_endorser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coach_club_endorser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
