# Generated by Django 4.2.4 on 2024-06-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0190_footballplayerendorsementrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
