# Generated by Django 4.2.4 on 2024-06-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0191_alter_club_club_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reg_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
