# Generated by Django 4.2.4 on 2024-07-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0195_customuser_otp_alter_customuser_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
