# Generated by Django 4.2.4 on 2024-07-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0196_alter_customuser_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_flag',
            field=models.BooleanField(default=False, verbose_name='flag'),
        ),
    ]
