# Generated by Django 4.2.4 on 2024-07-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0197_remove_customuser_otp_customuser_is_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballclub',
            name='address',
        ),
        migrations.RemoveField(
            model_name='footballclub',
            name='city',
        ),
        migrations.RemoveField(
            model_name='footballclub',
            name='country',
        ),
        migrations.RemoveField(
            model_name='footballclub',
            name='established_year',
        ),
    ]
