# Generated by Django 4.2.4 on 2024-07-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0198_remove_footballclub_address_remove_footballclub_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclub',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
