# Generated by Django 4.2.4 on 2024-07-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0199_alter_footballclub_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclubverificationdocument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
