# Generated by Django 4.2.4 on 2024-07-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0200_alter_footballclubverificationdocument_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footballclubverificationdocument',
            name='document_number',
        ),
        migrations.AddField(
            model_name='footballclubverificationdocument',
            name='document_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
