# Generated by Django 4.2.4 on 2024-07-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0201_remove_footballclubverificationdocument_document_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclubverificationdocument',
            name='license_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footballclubverificationdocument',
            name='document_type',
            field=models.CharField(default='jpg', max_length=100),
        ),
    ]
