# Generated by Django 4.2.4 on 2024-08-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0202_footballclubverificationdocument_license_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='league_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='league_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='sport_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
