# Generated by Django 4.2.4 on 2024-08-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0203_alter_league_league_name_alter_league_league_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballclubhistory',
            name='league_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
