# Generated by Django 4.2.4 on 2024-08-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0204_footballclubhistory_league_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballcoachcareerhistory',
            name='club_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
