# Generated by Django 4.2.4 on 2024-08-12 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0206_alter_sportprofiletype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='permanent_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to=settings.AUTH_USER_MODEL),
        ),
    ]
