# Generated by Django 4.2.4 on 2024-08-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0208_customuser_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclubverificationdocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='club_document/'),
        ),
        migrations.AlterField(
            model_name='footballclubverificationdocument',
            name='document_type',
            field=models.CharField(default='pdf', max_length=100),
        ),
    ]
