# Generated by Django 4.2.4 on 2024-08-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0209_alter_footballclubverificationdocument_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballclubhistory',
            name='achievement',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
