# Generated by Django 4.2.4 on 2024-08-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0210_alter_footballclubhistory_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentlicense',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='coachlicense',
            name='certificate',
        ),
        migrations.AddField(
            model_name='agentlicense',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='agent_cerificate/'),
        ),
        migrations.AddField(
            model_name='agentlicense',
            name='document_type',
            field=models.CharField(default='application/pdf', max_length=100),
        ),
        migrations.AddField(
            model_name='coachlicense',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='coach_cerificate/'),
        ),
        migrations.AddField(
            model_name='coachlicense',
            name='document_type',
            field=models.CharField(default='application/pdf', max_length=100),
        ),
    ]
